import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const governed = JSON.parse(fs.readFileSync(path.join(root, "config/compatibility.json"), "utf8"));

const model = {
  packageVersion: pkg.version,
  react: pkg.peerDependencies?.react,
  reactNative: pkg.peerDependencies?.["react-native"],
  node: pkg.engines?.node,
  expoSdk: governed.expoSdk,
  validatedConsumer: governed.validatedConsumer,
};

for (const [key, value] of Object.entries(model)) {
  if (value == null || value === "") throw new Error(`Missing compatibility field: ${key}`);
}

const output = `# Consumer Compatibility\n\n<!-- GENERATED by npm run docs:compat. Do not edit compatibility values manually. -->\n\n- Package candidate: \`${model.packageVersion}\`\n- React peer: \`${model.react}\`\n- React Native peer: \`${model.reactNative}\`\n- Node engine: \`${model.node}\`\n- Expo SDK validated baseline: \`${model.expoSdk}\`\n- Validated consumer: Expo \`${model.validatedConsumer.expo}\`, React Native \`${model.validatedConsumer.reactNative}\`, React \`${model.validatedConsumer.react}\`, ${model.validatedConsumer.runtime}.\n\nExpo is a governed validation baseline; it is not inferred from the React Native peer range.\n`;

const target = path.join(root, "docs/compatibility.md");
const mode = process.argv[2] ?? "write";
if (mode === "--check") {
  const actual = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  if (actual !== output) {
    console.error("docs/compatibility.md drifts from package.json or config/compatibility.json. Run npm run docs:compat.");
    process.exit(1);
  }
  console.log("Compatibility documentation is consistent.");
} else {
  fs.writeFileSync(target, output);
  console.log("Generated docs/compatibility.md");
}
